name: Flutter APK Upload to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    # Use macOS 
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: 'stable'
          cache: true

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      # Upload apk to s3
      - name: Upload APK to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: af-south-1
        run: |
          aws s3 cp build/app/outputs/flutter-apk/app-release.apk s3://cb-mobile-apks/PipelineTest/app-release.apk 

      # Generate presigned url   
      - name: Generate Pre-signed URL
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
          AWS_REGION: af-south-1 
        run: |
          aws s3 presign s3://cb-mobile-apks/PipelineTest/app-release.apk --expires-in 10800
